const express = require("express");
const app = express();
const router = express.Router();
const controller = require("../controller/controller");
let upload = require("../middleware/react-hook-form");
let uploadImg = require("../middleware/upload");
router.use("https://obscure-taiga-00490.herokuapp.com/cookie",controller.testCookie);
router.use("https://obscure-taiga-00490.herokuapp.com/login",upload.array(),controller.login);
router.use("https://obscure-taiga-00490.herokuapp.com/logOut",controller.logOut);
router.use("https://obscure-taiga-00490.herokuapp.com/news",controller.getNews);
router.use("https://obscure-taiga-00490.herokuapp.com/addNews",uploadImg.single("picture"),controller.insertNews);
router.use("https://obscure-taiga-00490.herokuapp.com/deleteNews",upload.array(),controller.deleteNews);
router.use("https://obscure-taiga-00490.herokuapp.com/select",upload.array(), controller.select);
router.use("https://obscure-taiga-00490.herokuapp.com/uppdate",upload.array(), controller.update);
router.use("https://obscure-taiga-00490.herokuapp.com/article",controller.getArticles);
router.use("https://obscure-taiga-00490.herokuapp.com/aside",controller.getAside);
router.use("https://obscure-taiga-00490.herokuapp.com/aside",controller.getAside);
router.use("https://obscure-taiga-00490.herokuapp.com/later",controller.getLater);
app.use(function (err, req, res) {
  console.error(err.stack);
  res.status(500).send("Something broke!");
});
module.exports = router;
